name: loki-backoffice
services:
  backoffice:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      - APP_NAME=loki-backoffice
      - APP_ADDRESS=0.0.0.0:8081
      - CLIENT_URL=http://localhost:3001
      - DATABASE_DSN=postgres://postgres:postgres@database:5432/loki-backoffice-development?sslmode=disable
      - TELEMETRY_URI=telemetry:4317
      - LOG_LEVEL=info
    networks:
      - loki-network
    volumes:
      - ./certs:/run/certs

networks:
  loki-network:
    name: loki-network
    external: true
