// Code generated by MockGen. DO NOT EDIT.
// Source: internal/config/middlewares/authentication.go
//
// Generated by this command:
//
//	mockgen -source=internal/config/middlewares/authentication.go -destination=internal/config/middlewares/authentication_mock.go -package=middlewares
//

// Package middlewares is a generated GoMock package.
package middlewares

import (
	http "net/http"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockAuthenticationMiddleware is a mock of AuthenticationMiddleware interface.
type MockAuthenticationMiddleware struct {
	ctrl     *gomock.Controller
	recorder *MockAuthenticationMiddlewareMockRecorder
	isgomock struct{}
}

// MockAuthenticationMiddlewareMockRecorder is the mock recorder for MockAuthenticationMiddleware.
type MockAuthenticationMiddlewareMockRecorder struct {
	mock *MockAuthenticationMiddleware
}

// NewMockAuthenticationMiddleware creates a new mock instance.
func NewMockAuthenticationMiddleware(ctrl *gomock.Controller) *MockAuthenticationMiddleware {
	mock := &MockAuthenticationMiddleware{ctrl: ctrl}
	mock.recorder = &MockAuthenticationMiddlewareMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuthenticationMiddleware) EXPECT() *MockAuthenticationMiddlewareMockRecorder {
	return m.recorder
}

// Authenticate mocks base method.
func (m *MockAuthenticationMiddleware) Authenticate(next http.Handler) http.Handler {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Authenticate", next)
	ret0, _ := ret[0].(http.Handler)
	return ret0
}

// Authenticate indicates an expected call of Authenticate.
func (mr *MockAuthenticationMiddlewareMockRecorder) Authenticate(next any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Authenticate", reflect.TypeOf((*MockAuthenticationMiddleware)(nil).Authenticate), next)
}
