// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: sso/v1/pagination.proto

package ssov1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// PaginatedListRequest is the request for the List method
type PaginatedListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         uint64                 `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        uint64                 `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaginatedListRequest) Reset() {
	*x = PaginatedListRequest{}
	mi := &file_sso_v1_pagination_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaginatedListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaginatedListRequest) ProtoMessage() {}

func (x *PaginatedListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sso_v1_pagination_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaginatedListRequest.ProtoReflect.Descriptor instead.
func (*PaginatedListRequest) Descriptor() ([]byte, []int) {
	return file_sso_v1_pagination_proto_rawDescGZIP(), []int{0}
}

func (x *PaginatedListRequest) GetLimit() uint64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *PaginatedListRequest) GetOffset() uint64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

// PaginationMeta pagination metadata
type PaginationMeta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          uint64                 `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Per           uint64                 `protobuf:"varint,2,opt,name=per,proto3" json:"per,omitempty"`
	Total         uint64                 `protobuf:"varint,3,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaginationMeta) Reset() {
	*x = PaginationMeta{}
	mi := &file_sso_v1_pagination_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaginationMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaginationMeta) ProtoMessage() {}

func (x *PaginationMeta) ProtoReflect() protoreflect.Message {
	mi := &file_sso_v1_pagination_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaginationMeta.ProtoReflect.Descriptor instead.
func (*PaginationMeta) Descriptor() ([]byte, []int) {
	return file_sso_v1_pagination_proto_rawDescGZIP(), []int{1}
}

func (x *PaginationMeta) GetPage() uint64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *PaginationMeta) GetPer() uint64 {
	if x != nil {
		return x.Per
	}
	return 0
}

func (x *PaginationMeta) GetTotal() uint64 {
	if x != nil {
		return x.Total
	}
	return 0
}

var File_sso_v1_pagination_proto protoreflect.FileDescriptor

const file_sso_v1_pagination_proto_rawDesc = "" +
	"\n" +
	"\x17sso/v1/pagination.proto\x12\x06sso.v1\x1a\x1bbuf/validate/validate.proto\"V\n" +
	"\x14PaginatedListRequest\x12\x1d\n" +
	"\x05limit\x18\x01 \x01(\x04B\a\xbaH\x042\x02(\x01R\x05limit\x12\x1f\n" +
	"\x06offset\x18\x02 \x01(\x04B\a\xbaH\x042\x02(\x01R\x06offset\"L\n" +
	"\x0ePaginationMeta\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x04R\x04page\x12\x10\n" +
	"\x03per\x18\x02 \x01(\x04R\x03per\x12\x14\n" +
	"\x05total\x18\x03 \x01(\x04R\x05totalB+Z)loki/internal/app/rpcs/proto/sso/v1;ssov1b\x06proto3"

var (
	file_sso_v1_pagination_proto_rawDescOnce sync.Once
	file_sso_v1_pagination_proto_rawDescData []byte
)

func file_sso_v1_pagination_proto_rawDescGZIP() []byte {
	file_sso_v1_pagination_proto_rawDescOnce.Do(func() {
		file_sso_v1_pagination_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sso_v1_pagination_proto_rawDesc), len(file_sso_v1_pagination_proto_rawDesc)))
	})
	return file_sso_v1_pagination_proto_rawDescData
}

var file_sso_v1_pagination_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_sso_v1_pagination_proto_goTypes = []any{
	(*PaginatedListRequest)(nil), // 0: sso.v1.PaginatedListRequest
	(*PaginationMeta)(nil),       // 1: sso.v1.PaginationMeta
}
var file_sso_v1_pagination_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_sso_v1_pagination_proto_init() }
func file_sso_v1_pagination_proto_init() {
	if File_sso_v1_pagination_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sso_v1_pagination_proto_rawDesc), len(file_sso_v1_pagination_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sso_v1_pagination_proto_goTypes,
		DependencyIndexes: file_sso_v1_pagination_proto_depIdxs,
		MessageInfos:      file_sso_v1_pagination_proto_msgTypes,
	}.Build()
	File_sso_v1_pagination_proto = out.File
	file_sso_v1_pagination_proto_goTypes = nil
	file_sso_v1_pagination_proto_depIdxs = nil
}
