// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: sso/v1/permission.proto

package ssov1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Permission represents a user permission object
type Permission struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Permission) Reset() {
	*x = Permission{}
	mi := &file_sso_v1_permission_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Permission) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Permission) ProtoMessage() {}

func (x *Permission) ProtoReflect() protoreflect.Message {
	mi := &file_sso_v1_permission_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Permission.ProtoReflect.Descriptor instead.
func (*Permission) Descriptor() ([]byte, []int) {
	return file_sso_v1_permission_proto_rawDescGZIP(), []int{0}
}

func (x *Permission) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Permission) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Permission) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

// ListPermissionsResponse is the response for the List method
type ListPermissionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []*Permission          `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	Meta          *PaginationMeta        `protobuf:"bytes,2,opt,name=meta,proto3" json:"meta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPermissionsResponse) Reset() {
	*x = ListPermissionsResponse{}
	mi := &file_sso_v1_permission_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPermissionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPermissionsResponse) ProtoMessage() {}

func (x *ListPermissionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sso_v1_permission_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPermissionsResponse.ProtoReflect.Descriptor instead.
func (*ListPermissionsResponse) Descriptor() ([]byte, []int) {
	return file_sso_v1_permission_proto_rawDescGZIP(), []int{1}
}

func (x *ListPermissionsResponse) GetData() []*Permission {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ListPermissionsResponse) GetMeta() *PaginationMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

// GetPermissionRequest is the request for the Get method
type GetPermissionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPermissionRequest) Reset() {
	*x = GetPermissionRequest{}
	mi := &file_sso_v1_permission_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPermissionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPermissionRequest) ProtoMessage() {}

func (x *GetPermissionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sso_v1_permission_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPermissionRequest.ProtoReflect.Descriptor instead.
func (*GetPermissionRequest) Descriptor() ([]byte, []int) {
	return file_sso_v1_permission_proto_rawDescGZIP(), []int{2}
}

func (x *GetPermissionRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// GetPermissionResponse is the response for the Get method
type GetPermissionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          *Permission            `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPermissionResponse) Reset() {
	*x = GetPermissionResponse{}
	mi := &file_sso_v1_permission_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPermissionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPermissionResponse) ProtoMessage() {}

func (x *GetPermissionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sso_v1_permission_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPermissionResponse.ProtoReflect.Descriptor instead.
func (*GetPermissionResponse) Descriptor() ([]byte, []int) {
	return file_sso_v1_permission_proto_rawDescGZIP(), []int{3}
}

func (x *GetPermissionResponse) GetData() *Permission {
	if x != nil {
		return x.Data
	}
	return nil
}

// CreatePermissionRequest is the request for the Create method
type CreatePermissionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePermissionRequest) Reset() {
	*x = CreatePermissionRequest{}
	mi := &file_sso_v1_permission_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePermissionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePermissionRequest) ProtoMessage() {}

func (x *CreatePermissionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sso_v1_permission_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePermissionRequest.ProtoReflect.Descriptor instead.
func (*CreatePermissionRequest) Descriptor() ([]byte, []int) {
	return file_sso_v1_permission_proto_rawDescGZIP(), []int{4}
}

func (x *CreatePermissionRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreatePermissionRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

// CreatePermissionResponse is the response for the Create method
type CreatePermissionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          *Permission            `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePermissionResponse) Reset() {
	*x = CreatePermissionResponse{}
	mi := &file_sso_v1_permission_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePermissionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePermissionResponse) ProtoMessage() {}

func (x *CreatePermissionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sso_v1_permission_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePermissionResponse.ProtoReflect.Descriptor instead.
func (*CreatePermissionResponse) Descriptor() ([]byte, []int) {
	return file_sso_v1_permission_proto_rawDescGZIP(), []int{5}
}

func (x *CreatePermissionResponse) GetData() *Permission {
	if x != nil {
		return x.Data
	}
	return nil
}

// UpdatePermissionRequest is the request for the Update method
type UpdatePermissionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePermissionRequest) Reset() {
	*x = UpdatePermissionRequest{}
	mi := &file_sso_v1_permission_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePermissionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePermissionRequest) ProtoMessage() {}

func (x *UpdatePermissionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sso_v1_permission_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePermissionRequest.ProtoReflect.Descriptor instead.
func (*UpdatePermissionRequest) Descriptor() ([]byte, []int) {
	return file_sso_v1_permission_proto_rawDescGZIP(), []int{6}
}

func (x *UpdatePermissionRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdatePermissionRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdatePermissionRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

// UpdatePermissionResponse is the response for the Update method
type UpdatePermissionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          *Permission            `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePermissionResponse) Reset() {
	*x = UpdatePermissionResponse{}
	mi := &file_sso_v1_permission_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePermissionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePermissionResponse) ProtoMessage() {}

func (x *UpdatePermissionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sso_v1_permission_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePermissionResponse.ProtoReflect.Descriptor instead.
func (*UpdatePermissionResponse) Descriptor() ([]byte, []int) {
	return file_sso_v1_permission_proto_rawDescGZIP(), []int{7}
}

func (x *UpdatePermissionResponse) GetData() *Permission {
	if x != nil {
		return x.Data
	}
	return nil
}

// DeletePermissionRequest is the request for the Delete method
type DeletePermissionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePermissionRequest) Reset() {
	*x = DeletePermissionRequest{}
	mi := &file_sso_v1_permission_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePermissionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePermissionRequest) ProtoMessage() {}

func (x *DeletePermissionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sso_v1_permission_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePermissionRequest.ProtoReflect.Descriptor instead.
func (*DeletePermissionRequest) Descriptor() ([]byte, []int) {
	return file_sso_v1_permission_proto_rawDescGZIP(), []int{8}
}

func (x *DeletePermissionRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

var File_sso_v1_permission_proto protoreflect.FileDescriptor

const file_sso_v1_permission_proto_rawDesc = "" +
	"\n" +
	"\x17sso/v1/permission.proto\x12\x06sso.v1\x1a\x1bbuf/validate/validate.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x17sso/v1/pagination.proto\"s\n" +
	"\n" +
	"Permission\x12\x18\n" +
	"\x02id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\x02id\x12\x1d\n" +
	"\x04name\x18\x02 \x01(\tB\t\xbaH\x06r\x04\x10\x01\x18dR\x04name\x12,\n" +
	"\vdescription\x18\x03 \x01(\tB\n" +
	"\xbaH\ar\x05\x10\x01\x18\x80\x10R\vdescription\"m\n" +
	"\x17ListPermissionsResponse\x12&\n" +
	"\x04data\x18\x01 \x03(\v2\x12.sso.v1.PermissionR\x04data\x12*\n" +
	"\x04meta\x18\x02 \x01(\v2\x16.sso.v1.PaginationMetaR\x04meta\"0\n" +
	"\x14GetPermissionRequest\x12\x18\n" +
	"\x02id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\x02id\"?\n" +
	"\x15GetPermissionResponse\x12&\n" +
	"\x04data\x18\x01 \x01(\v2\x12.sso.v1.PermissionR\x04data\"f\n" +
	"\x17CreatePermissionRequest\x12\x1d\n" +
	"\x04name\x18\x01 \x01(\tB\t\xbaH\x06r\x04\x10\x01\x18dR\x04name\x12,\n" +
	"\vdescription\x18\x02 \x01(\tB\n" +
	"\xbaH\ar\x05\x10\x01\x18\x80\x10R\vdescription\"B\n" +
	"\x18CreatePermissionResponse\x12&\n" +
	"\x04data\x18\x01 \x01(\v2\x12.sso.v1.PermissionR\x04data\"\x80\x01\n" +
	"\x17UpdatePermissionRequest\x12\x18\n" +
	"\x02id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\x02id\x12\x1d\n" +
	"\x04name\x18\x02 \x01(\tB\t\xbaH\x06r\x04\x10\x01\x18dR\x04name\x12,\n" +
	"\vdescription\x18\x03 \x01(\tB\n" +
	"\xbaH\ar\x05\x10\x01\x18\x80\x10R\vdescription\"B\n" +
	"\x18UpdatePermissionResponse\x12&\n" +
	"\x04data\x18\x01 \x01(\v2\x12.sso.v1.PermissionR\x04data\"3\n" +
	"\x17DeletePermissionRequest\x12\x18\n" +
	"\x02id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\x02id2\x85\x03\n" +
	"\x11PermissionService\x12G\n" +
	"\x04List\x12\x1c.sso.v1.PaginatedListRequest\x1a\x1f.sso.v1.ListPermissionsResponse\"\x00\x12D\n" +
	"\x03Get\x12\x1c.sso.v1.GetPermissionRequest\x1a\x1d.sso.v1.GetPermissionResponse\"\x00\x12M\n" +
	"\x06Create\x12\x1f.sso.v1.CreatePermissionRequest\x1a .sso.v1.CreatePermissionResponse\"\x00\x12M\n" +
	"\x06Update\x12\x1f.sso.v1.UpdatePermissionRequest\x1a .sso.v1.UpdatePermissionResponse\"\x00\x12C\n" +
	"\x06Delete\x12\x1f.sso.v1.DeletePermissionRequest\x1a\x16.google.protobuf.Empty\"\x00B+Z)loki/internal/app/rpcs/proto/sso/v1;ssov1b\x06proto3"

var (
	file_sso_v1_permission_proto_rawDescOnce sync.Once
	file_sso_v1_permission_proto_rawDescData []byte
)

func file_sso_v1_permission_proto_rawDescGZIP() []byte {
	file_sso_v1_permission_proto_rawDescOnce.Do(func() {
		file_sso_v1_permission_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sso_v1_permission_proto_rawDesc), len(file_sso_v1_permission_proto_rawDesc)))
	})
	return file_sso_v1_permission_proto_rawDescData
}

var file_sso_v1_permission_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_sso_v1_permission_proto_goTypes = []any{
	(*Permission)(nil),               // 0: sso.v1.Permission
	(*ListPermissionsResponse)(nil),  // 1: sso.v1.ListPermissionsResponse
	(*GetPermissionRequest)(nil),     // 2: sso.v1.GetPermissionRequest
	(*GetPermissionResponse)(nil),    // 3: sso.v1.GetPermissionResponse
	(*CreatePermissionRequest)(nil),  // 4: sso.v1.CreatePermissionRequest
	(*CreatePermissionResponse)(nil), // 5: sso.v1.CreatePermissionResponse
	(*UpdatePermissionRequest)(nil),  // 6: sso.v1.UpdatePermissionRequest
	(*UpdatePermissionResponse)(nil), // 7: sso.v1.UpdatePermissionResponse
	(*DeletePermissionRequest)(nil),  // 8: sso.v1.DeletePermissionRequest
	(*PaginationMeta)(nil),           // 9: sso.v1.PaginationMeta
	(*PaginatedListRequest)(nil),     // 10: sso.v1.PaginatedListRequest
	(*emptypb.Empty)(nil),            // 11: google.protobuf.Empty
}
var file_sso_v1_permission_proto_depIdxs = []int32{
	0,  // 0: sso.v1.ListPermissionsResponse.data:type_name -> sso.v1.Permission
	9,  // 1: sso.v1.ListPermissionsResponse.meta:type_name -> sso.v1.PaginationMeta
	0,  // 2: sso.v1.GetPermissionResponse.data:type_name -> sso.v1.Permission
	0,  // 3: sso.v1.CreatePermissionResponse.data:type_name -> sso.v1.Permission
	0,  // 4: sso.v1.UpdatePermissionResponse.data:type_name -> sso.v1.Permission
	10, // 5: sso.v1.PermissionService.List:input_type -> sso.v1.PaginatedListRequest
	2,  // 6: sso.v1.PermissionService.Get:input_type -> sso.v1.GetPermissionRequest
	4,  // 7: sso.v1.PermissionService.Create:input_type -> sso.v1.CreatePermissionRequest
	6,  // 8: sso.v1.PermissionService.Update:input_type -> sso.v1.UpdatePermissionRequest
	8,  // 9: sso.v1.PermissionService.Delete:input_type -> sso.v1.DeletePermissionRequest
	1,  // 10: sso.v1.PermissionService.List:output_type -> sso.v1.ListPermissionsResponse
	3,  // 11: sso.v1.PermissionService.Get:output_type -> sso.v1.GetPermissionResponse
	5,  // 12: sso.v1.PermissionService.Create:output_type -> sso.v1.CreatePermissionResponse
	7,  // 13: sso.v1.PermissionService.Update:output_type -> sso.v1.UpdatePermissionResponse
	11, // 14: sso.v1.PermissionService.Delete:output_type -> google.protobuf.Empty
	10, // [10:15] is the sub-list for method output_type
	5,  // [5:10] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_sso_v1_permission_proto_init() }
func file_sso_v1_permission_proto_init() {
	if File_sso_v1_permission_proto != nil {
		return
	}
	file_sso_v1_pagination_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sso_v1_permission_proto_rawDesc), len(file_sso_v1_permission_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sso_v1_permission_proto_goTypes,
		DependencyIndexes: file_sso_v1_permission_proto_depIdxs,
		MessageInfos:      file_sso_v1_permission_proto_msgTypes,
	}.Build()
	File_sso_v1_permission_proto = out.File
	file_sso_v1_permission_proto_goTypes = nil
	file_sso_v1_permission_proto_depIdxs = nil
}
