// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: sso/v1/token.proto

package ssov1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Token represents a JWT-token object
type Token struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Value         string                 `protobuf:"bytes,4,opt,name=value,proto3" json:"value,omitempty"`
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Token) Reset() {
	*x = Token{}
	mi := &file_sso_v1_token_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Token) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Token) ProtoMessage() {}

func (x *Token) ProtoReflect() protoreflect.Message {
	mi := &file_sso_v1_token_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Token.ProtoReflect.Descriptor instead.
func (*Token) Descriptor() ([]byte, []int) {
	return file_sso_v1_token_proto_rawDescGZIP(), []int{0}
}

func (x *Token) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Token) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Token) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Token) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *Token) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

// ListTokensResponse is the response for the List method
type ListTokensResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []*Token               `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	Meta          *PaginationMeta        `protobuf:"bytes,2,opt,name=meta,proto3" json:"meta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTokensResponse) Reset() {
	*x = ListTokensResponse{}
	mi := &file_sso_v1_token_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTokensResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTokensResponse) ProtoMessage() {}

func (x *ListTokensResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sso_v1_token_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTokensResponse.ProtoReflect.Descriptor instead.
func (*ListTokensResponse) Descriptor() ([]byte, []int) {
	return file_sso_v1_token_proto_rawDescGZIP(), []int{1}
}

func (x *ListTokensResponse) GetData() []*Token {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ListTokensResponse) GetMeta() *PaginationMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

// DeleteTokenRequest is the request for the Delete method
type DeleteTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTokenRequest) Reset() {
	*x = DeleteTokenRequest{}
	mi := &file_sso_v1_token_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTokenRequest) ProtoMessage() {}

func (x *DeleteTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sso_v1_token_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTokenRequest.ProtoReflect.Descriptor instead.
func (*DeleteTokenRequest) Descriptor() ([]byte, []int) {
	return file_sso_v1_token_proto_rawDescGZIP(), []int{2}
}

func (x *DeleteTokenRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

var File_sso_v1_token_proto protoreflect.FileDescriptor

const file_sso_v1_token_proto_rawDesc = "" +
	"\n" +
	"\x12sso/v1/token.proto\x12\x06sso.v1\x1a\x1bbuf/validate/validate.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x17sso/v1/pagination.proto\"\xd6\x01\n" +
	"\x05Token\x12\x18\n" +
	"\x02id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\x02id\x12!\n" +
	"\auser_id\x18\x02 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\x06userId\x126\n" +
	"\x04type\x18\x03 \x01(\tB\"\xbaH\x1fr\x1dR\faccess_tokenR\rrefresh_tokenR\x04type\x12\x1d\n" +
	"\x05value\x18\x04 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x05value\x129\n" +
	"\n" +
	"expires_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\"c\n" +
	"\x12ListTokensResponse\x12!\n" +
	"\x04data\x18\x01 \x03(\v2\r.sso.v1.TokenR\x04data\x12*\n" +
	"\x04meta\x18\x02 \x01(\v2\x16.sso.v1.PaginationMetaR\x04meta\".\n" +
	"\x12DeleteTokenRequest\x12\x18\n" +
	"\x02id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\x02id2\x92\x01\n" +
	"\fTokenService\x12B\n" +
	"\x04List\x12\x1c.sso.v1.PaginatedListRequest\x1a\x1a.sso.v1.ListTokensResponse\"\x00\x12>\n" +
	"\x06Delete\x12\x1a.sso.v1.DeleteTokenRequest\x1a\x16.google.protobuf.Empty\"\x00B+Z)loki/internal/app/rpcs/proto/sso/v1;ssov1b\x06proto3"

var (
	file_sso_v1_token_proto_rawDescOnce sync.Once
	file_sso_v1_token_proto_rawDescData []byte
)

func file_sso_v1_token_proto_rawDescGZIP() []byte {
	file_sso_v1_token_proto_rawDescOnce.Do(func() {
		file_sso_v1_token_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sso_v1_token_proto_rawDesc), len(file_sso_v1_token_proto_rawDesc)))
	})
	return file_sso_v1_token_proto_rawDescData
}

var file_sso_v1_token_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_sso_v1_token_proto_goTypes = []any{
	(*Token)(nil),                 // 0: sso.v1.Token
	(*ListTokensResponse)(nil),    // 1: sso.v1.ListTokensResponse
	(*DeleteTokenRequest)(nil),    // 2: sso.v1.DeleteTokenRequest
	(*timestamppb.Timestamp)(nil), // 3: google.protobuf.Timestamp
	(*PaginationMeta)(nil),        // 4: sso.v1.PaginationMeta
	(*PaginatedListRequest)(nil),  // 5: sso.v1.PaginatedListRequest
	(*emptypb.Empty)(nil),         // 6: google.protobuf.Empty
}
var file_sso_v1_token_proto_depIdxs = []int32{
	3, // 0: sso.v1.Token.expires_at:type_name -> google.protobuf.Timestamp
	0, // 1: sso.v1.ListTokensResponse.data:type_name -> sso.v1.Token
	4, // 2: sso.v1.ListTokensResponse.meta:type_name -> sso.v1.PaginationMeta
	5, // 3: sso.v1.TokenService.List:input_type -> sso.v1.PaginatedListRequest
	2, // 4: sso.v1.TokenService.Delete:input_type -> sso.v1.DeleteTokenRequest
	1, // 5: sso.v1.TokenService.List:output_type -> sso.v1.ListTokensResponse
	6, // 6: sso.v1.TokenService.Delete:output_type -> google.protobuf.Empty
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_sso_v1_token_proto_init() }
func file_sso_v1_token_proto_init() {
	if File_sso_v1_token_proto != nil {
		return
	}
	file_sso_v1_pagination_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sso_v1_token_proto_rawDesc), len(file_sso_v1_token_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sso_v1_token_proto_goTypes,
		DependencyIndexes: file_sso_v1_token_proto_depIdxs,
		MessageInfos:      file_sso_v1_token_proto_msgTypes,
	}.Build()
	File_sso_v1_token_proto = out.File
	file_sso_v1_token_proto_goTypes = nil
	file_sso_v1_token_proto_depIdxs = nil
}
