// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: sso/v1/user.proto

package ssov1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// User represents a user object
type User struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	IdentityNumber string                 `protobuf:"bytes,2,opt,name=identity_number,json=identityNumber,proto3" json:"identity_number,omitempty"`
	PersonalCode   string                 `protobuf:"bytes,3,opt,name=personal_code,json=personalCode,proto3" json:"personal_code,omitempty"`
	FirstName      string                 `protobuf:"bytes,4,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName       string                 `protobuf:"bytes,5,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	RoleIds        []string               `protobuf:"bytes,6,rep,name=role_ids,json=roleIds,proto3" json:"role_ids,omitempty"`
	ScopeIds       []string               `protobuf:"bytes,7,rep,name=scope_ids,json=scopeIds,proto3" json:"scope_ids,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_sso_v1_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_sso_v1_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_sso_v1_user_proto_rawDescGZIP(), []int{0}
}

func (x *User) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *User) GetIdentityNumber() string {
	if x != nil {
		return x.IdentityNumber
	}
	return ""
}

func (x *User) GetPersonalCode() string {
	if x != nil {
		return x.PersonalCode
	}
	return ""
}

func (x *User) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *User) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *User) GetRoleIds() []string {
	if x != nil {
		return x.RoleIds
	}
	return nil
}

func (x *User) GetScopeIds() []string {
	if x != nil {
		return x.ScopeIds
	}
	return nil
}

// ListUsersResponse is the response for the List method
type ListUsersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []*User                `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	Meta          *PaginationMeta        `protobuf:"bytes,2,opt,name=meta,proto3" json:"meta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUsersResponse) Reset() {
	*x = ListUsersResponse{}
	mi := &file_sso_v1_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUsersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUsersResponse) ProtoMessage() {}

func (x *ListUsersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sso_v1_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUsersResponse.ProtoReflect.Descriptor instead.
func (*ListUsersResponse) Descriptor() ([]byte, []int) {
	return file_sso_v1_user_proto_rawDescGZIP(), []int{1}
}

func (x *ListUsersResponse) GetData() []*User {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ListUsersResponse) GetMeta() *PaginationMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

// GetUserRequest is the request for the Get method
type GetUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserRequest) Reset() {
	*x = GetUserRequest{}
	mi := &file_sso_v1_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserRequest) ProtoMessage() {}

func (x *GetUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sso_v1_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserRequest.ProtoReflect.Descriptor instead.
func (*GetUserRequest) Descriptor() ([]byte, []int) {
	return file_sso_v1_user_proto_rawDescGZIP(), []int{2}
}

func (x *GetUserRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// GetUserResponse is the response for the Get method
type GetUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          *User                  `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserResponse) Reset() {
	*x = GetUserResponse{}
	mi := &file_sso_v1_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserResponse) ProtoMessage() {}

func (x *GetUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sso_v1_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserResponse.ProtoReflect.Descriptor instead.
func (*GetUserResponse) Descriptor() ([]byte, []int) {
	return file_sso_v1_user_proto_rawDescGZIP(), []int{3}
}

func (x *GetUserResponse) GetData() *User {
	if x != nil {
		return x.Data
	}
	return nil
}

// CreateUserRequest is the request for the Create method
type CreateUserRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	IdentityNumber string                 `protobuf:"bytes,1,opt,name=identity_number,json=identityNumber,proto3" json:"identity_number,omitempty"`
	PersonalCode   string                 `protobuf:"bytes,2,opt,name=personal_code,json=personalCode,proto3" json:"personal_code,omitempty"`
	FirstName      string                 `protobuf:"bytes,3,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName       string                 `protobuf:"bytes,4,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	RoleIds        []string               `protobuf:"bytes,5,rep,name=role_ids,json=roleIds,proto3" json:"role_ids,omitempty"`
	ScopeIds       []string               `protobuf:"bytes,6,rep,name=scope_ids,json=scopeIds,proto3" json:"scope_ids,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateUserRequest) Reset() {
	*x = CreateUserRequest{}
	mi := &file_sso_v1_user_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserRequest) ProtoMessage() {}

func (x *CreateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sso_v1_user_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserRequest.ProtoReflect.Descriptor instead.
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return file_sso_v1_user_proto_rawDescGZIP(), []int{4}
}

func (x *CreateUserRequest) GetIdentityNumber() string {
	if x != nil {
		return x.IdentityNumber
	}
	return ""
}

func (x *CreateUserRequest) GetPersonalCode() string {
	if x != nil {
		return x.PersonalCode
	}
	return ""
}

func (x *CreateUserRequest) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *CreateUserRequest) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *CreateUserRequest) GetRoleIds() []string {
	if x != nil {
		return x.RoleIds
	}
	return nil
}

func (x *CreateUserRequest) GetScopeIds() []string {
	if x != nil {
		return x.ScopeIds
	}
	return nil
}

// CreateUserResponse is the response for the Create method
type CreateUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          *User                  `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserResponse) Reset() {
	*x = CreateUserResponse{}
	mi := &file_sso_v1_user_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserResponse) ProtoMessage() {}

func (x *CreateUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sso_v1_user_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserResponse.ProtoReflect.Descriptor instead.
func (*CreateUserResponse) Descriptor() ([]byte, []int) {
	return file_sso_v1_user_proto_rawDescGZIP(), []int{5}
}

func (x *CreateUserResponse) GetData() *User {
	if x != nil {
		return x.Data
	}
	return nil
}

// UpdateUserRequest is the request for the Update method
type UpdateUserRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	IdentityNumber string                 `protobuf:"bytes,2,opt,name=identity_number,json=identityNumber,proto3" json:"identity_number,omitempty"`
	PersonalCode   string                 `protobuf:"bytes,3,opt,name=personal_code,json=personalCode,proto3" json:"personal_code,omitempty"`
	FirstName      string                 `protobuf:"bytes,4,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName       string                 `protobuf:"bytes,5,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	RoleIds        []string               `protobuf:"bytes,6,rep,name=role_ids,json=roleIds,proto3" json:"role_ids,omitempty"`
	ScopeIds       []string               `protobuf:"bytes,7,rep,name=scope_ids,json=scopeIds,proto3" json:"scope_ids,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UpdateUserRequest) Reset() {
	*x = UpdateUserRequest{}
	mi := &file_sso_v1_user_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserRequest) ProtoMessage() {}

func (x *UpdateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sso_v1_user_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserRequest.ProtoReflect.Descriptor instead.
func (*UpdateUserRequest) Descriptor() ([]byte, []int) {
	return file_sso_v1_user_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateUserRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateUserRequest) GetIdentityNumber() string {
	if x != nil {
		return x.IdentityNumber
	}
	return ""
}

func (x *UpdateUserRequest) GetPersonalCode() string {
	if x != nil {
		return x.PersonalCode
	}
	return ""
}

func (x *UpdateUserRequest) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *UpdateUserRequest) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *UpdateUserRequest) GetRoleIds() []string {
	if x != nil {
		return x.RoleIds
	}
	return nil
}

func (x *UpdateUserRequest) GetScopeIds() []string {
	if x != nil {
		return x.ScopeIds
	}
	return nil
}

// UpdateUserResponse is the response for the Update method
type UpdateUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          *User                  `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserResponse) Reset() {
	*x = UpdateUserResponse{}
	mi := &file_sso_v1_user_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserResponse) ProtoMessage() {}

func (x *UpdateUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sso_v1_user_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserResponse.ProtoReflect.Descriptor instead.
func (*UpdateUserResponse) Descriptor() ([]byte, []int) {
	return file_sso_v1_user_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateUserResponse) GetData() *User {
	if x != nil {
		return x.Data
	}
	return nil
}

// DeleteUserRequest is the request for the Delete method
type DeleteUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUserRequest) Reset() {
	*x = DeleteUserRequest{}
	mi := &file_sso_v1_user_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserRequest) ProtoMessage() {}

func (x *DeleteUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sso_v1_user_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserRequest.ProtoReflect.Descriptor instead.
func (*DeleteUserRequest) Descriptor() ([]byte, []int) {
	return file_sso_v1_user_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteUserRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

var File_sso_v1_user_proto protoreflect.FileDescriptor

const file_sso_v1_user_proto_rawDesc = "" +
	"\n" +
	"\x11sso/v1/user.proto\x12\x06sso.v1\x1a\x1bbuf/validate/validate.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x17sso/v1/pagination.proto\"\xac\x02\n" +
	"\x04User\x12\x18\n" +
	"\x02id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\x02id\x122\n" +
	"\x0fidentity_number\x18\x02 \x01(\tB\t\xbaH\x06r\x04\x10\x0f\x18\x14R\x0eidentityNumber\x12.\n" +
	"\rpersonal_code\x18\x03 \x01(\tB\t\xbaH\x06r\x04\x10\v\x18\x14R\fpersonalCode\x12(\n" +
	"\n" +
	"first_name\x18\x04 \x01(\tB\t\xbaH\x06r\x04\x10\x01\x182R\tfirstName\x12&\n" +
	"\tlast_name\x18\x05 \x01(\tB\t\xbaH\x06r\x04\x10\x01\x182R\blastName\x12(\n" +
	"\brole_ids\x18\x06 \x03(\tB\r\xbaH\n" +
	"\x92\x01\a\"\x05r\x03\xb0\x01\x01R\aroleIds\x12*\n" +
	"\tscope_ids\x18\a \x03(\tB\r\xbaH\n" +
	"\x92\x01\a\"\x05r\x03\xb0\x01\x01R\bscopeIds\"a\n" +
	"\x11ListUsersResponse\x12 \n" +
	"\x04data\x18\x01 \x03(\v2\f.sso.v1.UserR\x04data\x12*\n" +
	"\x04meta\x18\x02 \x01(\v2\x16.sso.v1.PaginationMetaR\x04meta\"*\n" +
	"\x0eGetUserRequest\x12\x18\n" +
	"\x02id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\x02id\"3\n" +
	"\x0fGetUserResponse\x12 \n" +
	"\x04data\x18\x01 \x01(\v2\f.sso.v1.UserR\x04data\"\x9f\x02\n" +
	"\x11CreateUserRequest\x122\n" +
	"\x0fidentity_number\x18\x01 \x01(\tB\t\xbaH\x06r\x04\x10\x0f\x18\x14R\x0eidentityNumber\x12.\n" +
	"\rpersonal_code\x18\x02 \x01(\tB\t\xbaH\x06r\x04\x10\v\x18\x14R\fpersonalCode\x12(\n" +
	"\n" +
	"first_name\x18\x03 \x01(\tB\t\xbaH\x06r\x04\x10\x01\x182R\tfirstName\x12&\n" +
	"\tlast_name\x18\x04 \x01(\tB\t\xbaH\x06r\x04\x10\x01\x182R\blastName\x12(\n" +
	"\brole_ids\x18\x05 \x03(\tB\r\xbaH\n" +
	"\x92\x01\a\"\x05r\x03\xb0\x01\x01R\aroleIds\x12*\n" +
	"\tscope_ids\x18\x06 \x03(\tB\r\xbaH\n" +
	"\x92\x01\a\"\x05r\x03\xb0\x01\x01R\bscopeIds\"6\n" +
	"\x12CreateUserResponse\x12 \n" +
	"\x04data\x18\x01 \x01(\v2\f.sso.v1.UserR\x04data\"\xb9\x02\n" +
	"\x11UpdateUserRequest\x12\x18\n" +
	"\x02id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\x02id\x122\n" +
	"\x0fidentity_number\x18\x02 \x01(\tB\t\xbaH\x06r\x04\x10\x0f\x18\x14R\x0eidentityNumber\x12.\n" +
	"\rpersonal_code\x18\x03 \x01(\tB\t\xbaH\x06r\x04\x10\v\x18\x14R\fpersonalCode\x12(\n" +
	"\n" +
	"first_name\x18\x04 \x01(\tB\t\xbaH\x06r\x04\x10\x01\x182R\tfirstName\x12&\n" +
	"\tlast_name\x18\x05 \x01(\tB\t\xbaH\x06r\x04\x10\x01\x182R\blastName\x12(\n" +
	"\brole_ids\x18\x06 \x03(\tB\r\xbaH\n" +
	"\x92\x01\a\"\x05r\x03\xb0\x01\x01R\aroleIds\x12*\n" +
	"\tscope_ids\x18\a \x03(\tB\r\xbaH\n" +
	"\x92\x01\a\"\x05r\x03\xb0\x01\x01R\bscopeIds\"6\n" +
	"\x12UpdateUserResponse\x12 \n" +
	"\x04data\x18\x01 \x01(\v2\f.sso.v1.UserR\x04data\"-\n" +
	"\x11DeleteUserRequest\x12\x18\n" +
	"\x02id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\x02id2\xcf\x02\n" +
	"\vUserService\x12A\n" +
	"\x04List\x12\x1c.sso.v1.PaginatedListRequest\x1a\x19.sso.v1.ListUsersResponse\"\x00\x128\n" +
	"\x03Get\x12\x16.sso.v1.GetUserRequest\x1a\x17.sso.v1.GetUserResponse\"\x00\x12A\n" +
	"\x06Create\x12\x19.sso.v1.CreateUserRequest\x1a\x1a.sso.v1.CreateUserResponse\"\x00\x12A\n" +
	"\x06Update\x12\x19.sso.v1.UpdateUserRequest\x1a\x1a.sso.v1.UpdateUserResponse\"\x00\x12=\n" +
	"\x06Delete\x12\x19.sso.v1.DeleteUserRequest\x1a\x16.google.protobuf.Empty\"\x00B+Z)loki/internal/app/rpcs/proto/sso/v1;ssov1b\x06proto3"

var (
	file_sso_v1_user_proto_rawDescOnce sync.Once
	file_sso_v1_user_proto_rawDescData []byte
)

func file_sso_v1_user_proto_rawDescGZIP() []byte {
	file_sso_v1_user_proto_rawDescOnce.Do(func() {
		file_sso_v1_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sso_v1_user_proto_rawDesc), len(file_sso_v1_user_proto_rawDesc)))
	})
	return file_sso_v1_user_proto_rawDescData
}

var file_sso_v1_user_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_sso_v1_user_proto_goTypes = []any{
	(*User)(nil),                 // 0: sso.v1.User
	(*ListUsersResponse)(nil),    // 1: sso.v1.ListUsersResponse
	(*GetUserRequest)(nil),       // 2: sso.v1.GetUserRequest
	(*GetUserResponse)(nil),      // 3: sso.v1.GetUserResponse
	(*CreateUserRequest)(nil),    // 4: sso.v1.CreateUserRequest
	(*CreateUserResponse)(nil),   // 5: sso.v1.CreateUserResponse
	(*UpdateUserRequest)(nil),    // 6: sso.v1.UpdateUserRequest
	(*UpdateUserResponse)(nil),   // 7: sso.v1.UpdateUserResponse
	(*DeleteUserRequest)(nil),    // 8: sso.v1.DeleteUserRequest
	(*PaginationMeta)(nil),       // 9: sso.v1.PaginationMeta
	(*PaginatedListRequest)(nil), // 10: sso.v1.PaginatedListRequest
	(*emptypb.Empty)(nil),        // 11: google.protobuf.Empty
}
var file_sso_v1_user_proto_depIdxs = []int32{
	0,  // 0: sso.v1.ListUsersResponse.data:type_name -> sso.v1.User
	9,  // 1: sso.v1.ListUsersResponse.meta:type_name -> sso.v1.PaginationMeta
	0,  // 2: sso.v1.GetUserResponse.data:type_name -> sso.v1.User
	0,  // 3: sso.v1.CreateUserResponse.data:type_name -> sso.v1.User
	0,  // 4: sso.v1.UpdateUserResponse.data:type_name -> sso.v1.User
	10, // 5: sso.v1.UserService.List:input_type -> sso.v1.PaginatedListRequest
	2,  // 6: sso.v1.UserService.Get:input_type -> sso.v1.GetUserRequest
	4,  // 7: sso.v1.UserService.Create:input_type -> sso.v1.CreateUserRequest
	6,  // 8: sso.v1.UserService.Update:input_type -> sso.v1.UpdateUserRequest
	8,  // 9: sso.v1.UserService.Delete:input_type -> sso.v1.DeleteUserRequest
	1,  // 10: sso.v1.UserService.List:output_type -> sso.v1.ListUsersResponse
	3,  // 11: sso.v1.UserService.Get:output_type -> sso.v1.GetUserResponse
	5,  // 12: sso.v1.UserService.Create:output_type -> sso.v1.CreateUserResponse
	7,  // 13: sso.v1.UserService.Update:output_type -> sso.v1.UpdateUserResponse
	11, // 14: sso.v1.UserService.Delete:output_type -> google.protobuf.Empty
	10, // [10:15] is the sub-list for method output_type
	5,  // [5:10] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_sso_v1_user_proto_init() }
func file_sso_v1_user_proto_init() {
	if File_sso_v1_user_proto != nil {
		return
	}
	file_sso_v1_pagination_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sso_v1_user_proto_rawDesc), len(file_sso_v1_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sso_v1_user_proto_goTypes,
		DependencyIndexes: file_sso_v1_user_proto_depIdxs,
		MessageInfos:      file_sso_v1_user_proto_msgTypes,
	}.Build()
	File_sso_v1_user_proto = out.File
	file_sso_v1_user_proto_goTypes = nil
	file_sso_v1_user_proto_depIdxs = nil
}
