// Code generated by MockGen. DO NOT EDIT.
// Source: internal/app/services/permissions.go
//
// Generated by this command:
//
//	mockgen -source=internal/app/services/permissions.go -destination=internal/app/services/permissions_mock.go -package=services
//

// Package services is a generated GoMock package.
package services

import (
	context "context"
	models "loki-backoffice/internal/app/models"
	reflect "reflect"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockPermissions is a mock of Permissions interface.
type MockPermissions struct {
	ctrl     *gomock.Controller
	recorder *MockPermissionsMockRecorder
	isgomock struct{}
}

// MockPermissionsMockRecorder is the mock recorder for MockPermissions.
type MockPermissionsMockRecorder struct {
	mock *MockPermissions
}

// NewMockPermissions creates a new mock instance.
func NewMockPermissions(ctrl *gomock.Controller) *MockPermissions {
	mock := &MockPermissions{ctrl: ctrl}
	mock.recorder = &MockPermissionsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPermissions) EXPECT() *MockPermissionsMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockPermissions) Create(ctx context.Context, params *models.Permission) (*models.Permission, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, params)
	ret0, _ := ret[0].(*models.Permission)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockPermissionsMockRecorder) Create(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockPermissions)(nil).Create), ctx, params)
}

// Delete mocks base method.
func (m *MockPermissions) Delete(ctx context.Context, id uuid.UUID) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Delete indicates an expected call of Delete.
func (mr *MockPermissionsMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockPermissions)(nil).Delete), ctx, id)
}

// FindById mocks base method.
func (m *MockPermissions) FindById(ctx context.Context, id uuid.UUID) (*models.Permission, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindById", ctx, id)
	ret0, _ := ret[0].(*models.Permission)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindById indicates an expected call of FindById.
func (mr *MockPermissionsMockRecorder) FindById(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindById", reflect.TypeOf((*MockPermissions)(nil).FindById), ctx, id)
}

// List mocks base method.
func (m *MockPermissions) List(ctx context.Context, pagination *Pagination) ([]models.Permission, uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, pagination)
	ret0, _ := ret[0].([]models.Permission)
	ret1, _ := ret[1].(uint64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// List indicates an expected call of List.
func (mr *MockPermissionsMockRecorder) List(ctx, pagination any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockPermissions)(nil).List), ctx, pagination)
}

// Update mocks base method.
func (m *MockPermissions) Update(ctx context.Context, params *models.Permission) (*models.Permission, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, params)
	ret0, _ := ret[0].(*models.Permission)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockPermissionsMockRecorder) Update(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockPermissions)(nil).Update), ctx, params)
}
