// Code generated by MockGen. DO NOT EDIT.
// Source: internal/app/services/scopes.go
//
// Generated by this command:
//
//	mockgen -source=internal/app/services/scopes.go -destination=internal/app/services/scopes_mock.go -package=services
//

// Package services is a generated GoMock package.
package services

import (
	context "context"
	models "loki-backoffice/internal/app/models"
	reflect "reflect"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockScopes is a mock of Scopes interface.
type MockScopes struct {
	ctrl     *gomock.Controller
	recorder *MockScopesMockRecorder
	isgomock struct{}
}

// MockScopesMockRecorder is the mock recorder for MockScopes.
type MockScopesMockRecorder struct {
	mock *MockScopes
}

// NewMockScopes creates a new mock instance.
func NewMockScopes(ctrl *gomock.Controller) *MockScopes {
	mock := &MockScopes{ctrl: ctrl}
	mock.recorder = &MockScopesMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockScopes) EXPECT() *MockScopesMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockScopes) Create(ctx context.Context, params *models.Scope) (*models.Scope, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, params)
	ret0, _ := ret[0].(*models.Scope)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockScopesMockRecorder) Create(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockScopes)(nil).Create), ctx, params)
}

// Delete mocks base method.
func (m *MockScopes) Delete(ctx context.Context, id uuid.UUID) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Delete indicates an expected call of Delete.
func (mr *MockScopesMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockScopes)(nil).Delete), ctx, id)
}

// FindById mocks base method.
func (m *MockScopes) FindById(ctx context.Context, id uuid.UUID) (*models.Scope, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindById", ctx, id)
	ret0, _ := ret[0].(*models.Scope)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindById indicates an expected call of FindById.
func (mr *MockScopesMockRecorder) FindById(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindById", reflect.TypeOf((*MockScopes)(nil).FindById), ctx, id)
}

// List mocks base method.
func (m *MockScopes) List(ctx context.Context, pagination *Pagination) ([]models.Scope, uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, pagination)
	ret0, _ := ret[0].([]models.Scope)
	ret1, _ := ret[1].(uint64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// List indicates an expected call of List.
func (mr *MockScopesMockRecorder) List(ctx, pagination any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockScopes)(nil).List), ctx, pagination)
}

// Update mocks base method.
func (m *MockScopes) Update(ctx context.Context, params *models.Scope) (*models.Scope, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, params)
	ret0, _ := ret[0].(*models.Scope)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockScopesMockRecorder) Update(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockScopes)(nil).Update), ctx, params)
}
