// Code generated by MockGen. DO NOT EDIT.
// Source: internal/app/controllers/roles.go
//
// Generated by this command:
//
//	mockgen -source=internal/app/controllers/roles.go -destination=internal/app/controllers/roles_mock.go -package=controllers
//

// Package controllers is a generated GoMock package.
package controllers

import (
	http "net/http"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockRolesController is a mock of RolesController interface.
type MockRolesController struct {
	ctrl     *gomock.Controller
	recorder *MockRolesControllerMockRecorder
	isgomock struct{}
}

// MockRolesControllerMockRecorder is the mock recorder for MockRolesController.
type MockRolesControllerMockRecorder struct {
	mock *MockRolesController
}

// NewMockRolesController creates a new mock instance.
func NewMockRolesController(ctrl *gomock.Controller) *MockRolesController {
	mock := &MockRolesController{ctrl: ctrl}
	mock.recorder = &MockRolesControllerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRolesController) EXPECT() *MockRolesControllerMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockRolesController) Create(w http.ResponseWriter, r *http.Request) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Create", w, r)
}

// Create indicates an expected call of Create.
func (mr *MockRolesControllerMockRecorder) Create(w, r any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockRolesController)(nil).Create), w, r)
}

// Delete mocks base method.
func (m *MockRolesController) Delete(w http.ResponseWriter, r *http.Request) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Delete", w, r)
}

// Delete indicates an expected call of Delete.
func (mr *MockRolesControllerMockRecorder) Delete(w, r any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockRolesController)(nil).Delete), w, r)
}

// Get mocks base method.
func (m *MockRolesController) Get(w http.ResponseWriter, r *http.Request) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Get", w, r)
}

// Get indicates an expected call of Get.
func (mr *MockRolesControllerMockRecorder) Get(w, r any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockRolesController)(nil).Get), w, r)
}

// List mocks base method.
func (m *MockRolesController) List(w http.ResponseWriter, r *http.Request) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "List", w, r)
}

// List indicates an expected call of List.
func (mr *MockRolesControllerMockRecorder) List(w, r any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockRolesController)(nil).List), w, r)
}

// Update mocks base method.
func (m *MockRolesController) Update(w http.ResponseWriter, r *http.Request) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Update", w, r)
}

// Update indicates an expected call of Update.
func (mr *MockRolesControllerMockRecorder) Update(w, r any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockRolesController)(nil).Update), w, r)
}
